#!/bin/bash
#
# Very simple test to verify that nested tests and basic command line
# expansion works.
#
# See README.selftest for more information
#

. ${0%/*}/functions

testbus_group_begin $0

TESTBUS_HOST=`testbus_claim_host`

testbus_test_begin subtest0
testbus_run_command --host $TESTBUS_HOST /bin/true

testbus_test_begin subtest1
testbus_run_command --host $TESTBUS_HOST /bin/true

testbus_test_success

test -n "$TESTCASE_TEMPDIR" || testbus_exit_fail "Missing tempdir"
groupfile=$TESTCASE_TEMPDIR/groupfile
echo 43 > $groupfile
__testbus_upload_file --context $TESTCASE_HANDLE $groupfile foobar

testbus_test_begin subtest2

test -n "$TESTCASE_TEMPDIR" || testbus_exit_fail "Missing tempdir"
testfile=$TESTCASE_TEMPDIR/testfile
echo 42 > $testfile

__testbus_upload_file --context $TESTCASE_HANDLE $testfile foobar

response=`testbus_run_command --host $TESTBUS_HOST /bin/cat "%{file:foobar}"`
if [ "$response" != "42" ]; then
	echo "expected answer 42; instead I got \"$response\""
	testbus_test_failure
fi >&2

testbus_test_success

testbus_group_begin nested-group
testbus_group_begin nested-even-deeper

testbus_test_begin run
testbus_run_command --host $TESTBUS_HOST /bin/true

# This should clean up everything implicitly
testbus_exit
