#!/bin/bash
#
# Very simple test to verify that the agent that's needed to run all the
# others tests is there.
#

# TESTBUS_SELFTEST_DEBUG=all

. ${0%/*}/../functions

# Override the timeout for claiming the host.
# Bringing up a VM guest can take some time, especially if it goes
# through a firstboot stage first.
TESTBUS_CLAIM_TIMEOUT=240

testbus_group_begin agent

testbus_test_begin verify_agent1
TESTBUS_HOST=`testbus_claim_host`
testbus_upload_file $TESTBUS_HOST /etc/SuSE-release /etc/upload-test
testbus_download_file $TESTBUS_HOST /etc/upload-test /tmp/download-test
if ! cmp /etc/SuSE-release /tmp/download-test; then
	echo "File uploaded to agent and downloaded again morphed in transit" >&2
	diff -u /etc/SuSE-release /tmp/download-test >&2
	testbus_test_failure
fi
rm -f /tmp/download-test
testbus_test_success

testbus_test_begin verify_agent2
testbus_claim_node sut

testbus_node_upload_file sut /etc/SuSE-release /etc/upload-test
testbus_node_download_file sut /etc/upload-test /tmp/download-test
if ! cmp /etc/SuSE-release /tmp/download-test; then
	echo "File uploaded to agent and downloaded again morphed in transit" >&2
	diff -u /etc/SuSE-release /tmp/download-test >&2
	testbus_test_failure
fi
rm -f /tmp/download-test
testbus_test_success

testbus_group_finish
testbus_exit
