#!/bin/bash
#
# Very simple test to verify that the basic functionality works
#
# For this to work, you need to run both master and agent on your local
# host.
#

. ${0%/*}/functions

testbus_init_test $0

TESTBUS_HOST=`testbus_claim_host`

testbus_run_command --host $TESTBUS_HOST /bin/true

if testbus_run_command --host $TESTBUS_HOST /bin/false; then
	echo "client does not propagate remote command's exit status" >&2
	exit 1
fi

expect=$TESTBUS_TEMPDIR/expect
/usr/bin/wc < /etc/hosts > $expect

stdout=$TESTBUS_TEMPDIR/stdout
testbus_run_command --host $TESTBUS_HOST --send-stdin /usr/bin/wc < /etc/hosts >$stdout

diff=$TESTBUS_TEMPDIR/diff
if ! diff -bu $stdout $expect >$diff; then
	echo "Command output differs between local host and SUT"
	echo "---"
	cat $diff
	echo "---"
	exit 1
fi >&2

testbus_call show-xml --raw > $TESTBUS_TEMPDIR/xml-tree-after
if cmp -s $TESTBUS_TEMPDIR/xml-tree-before $TESTBUS_TEMPDIR/xml-tree-after; then
	echo "Testbus object tree not clean after test run"
	echo "Differences before/after"
	diff -u $TESTBUS_TEMPDIR/xml-tree-before $TESTBUS_TEMPDIR/xml-tree-after
	exit 1
fi >&2

testbus_finish_test
echo "All tests completed successfully"
