#!/bin/bash
#
# Copyright (C) 2014 Olaf Kirch <okir@suse.de>
#
# Start a KVM instance with DBus forwarding; optionally installing
# some additional RPMs inside.
#
# For instance, you invoke it as
#
# testbus-control-kvm \
#	--add-rpm testbus-agent-kvm-0.1-0.x86_64.rpm \
#	client sle11-image.qcow2
#
# Note that this script always copies the provided image, so changes are
# never retained across restarts.
#

. /usr/share/testbus/control.functions

command=$1; shift
case $command in
start)
	testbus_kvm_start "$@";;
firstboot)
	testbus_kvm_firstboot "$@";;
stop)
	testbus_kvm_stop "$@";;
*)
	fatal "$0: unsupported command $command";;
esac
