#!/bin/bash
#
# This is a draft idea of how headers for testbus scripts
# could be used to drive the setup
##################################################################
# Start-Testbus-Requirements
# Instances		2
# Bridged-Network	yes
# Instance-NICs		1
# End-Testbus-Requirements
##################################################################

USE_YAST=false

# TESTBUS_SELFTEST_DEBUG=all

. /usr/share/testbus/functions

TMPDIR=/tmp/testbus-yp
mkdir -p $TMPDIR

# Override the timeout for claiming the host.
# Bringing up a VM guest can take some time, especially if it goes
# through a firstboot stage first.
TESTBUS_CLAIM_TIMEOUT=240

function __run_client {
	testbus_run_command --host $NFS_CLIENT "$@"
}

function run_client {

	if !  __run_client "$@"; then
		testbus_test_failure
		return 1;
	fi
	return 0
}

function run_client_script {
	run_client --host $NFS_CLIENT --send-script "$@"
}

function __run_server {
	testbus_run_command --host $NFS_SERVER "$@"
}

function run_server {
	if ! __run_server "$@"; then
		testbus_test_failure
		return 1
	fi
	return 0
}

function server_update_hosts {

	hostfile="$TESTCASE_TEMPDIR/hosts.server"
	testbus_download_file $NFS_SERVER /etc/hosts $hostfile
	echo "$*" >> $hostfile
	testbus_upload_file $NFS_SERVER $hostfile /etc/hosts
}

function client_update_hosts {

	hostfile="$TESTCASE_TEMPDIR/hosts.client"
	testbus_download_file $NFS_CLIENT /etc/hosts $hostfile
	echo "$*" >> $hostfile
	testbus_upload_file $NFS_CLIENT $hostfile /etc/hosts
}

function server_write_exports {

	testbus_upload_file $NFS_SERVER "$@" /etc/exports
	run_server /etc/init.d/nfsserver reload

	echo "exports file now:"
	testbus_download_file $NFS_SERVER /etc/exports -
}

##################################################################
# Start testing
##################################################################
testbus_group_begin $0

NFS_SERVER=`testbus_claim_host --role server`
test -n "$NFS_SERVER" || testbus_exit_fail "unable to claim NFS server"

NFS_CLIENT=`testbus_claim_host --role client`
test -n "$NFS_CLIENT" || testbus_exit_fail "unable to claim NFS client"

NFS_SERVER_IP=`testbus_getenv_nonempty $NFS_SERVER primary_ip`
NFS_CLIENT_IP=`testbus_getenv_nonempty $NFS_CLIENT primary_ip`

NFS_SERVER_NAME=`testbus_getenv_nonempty $NFS_SERVER hostname`
NFS_CLIENT_NAME=`testbus_getenv_nonempty $NFS_CLIENT hostname`

cat <<EOF
Claimed hosts
Server:  $NFS_SERVER_NAME ($NFS_SERVER_IP)
Client:  $NFS_CLIENT_NAME ($NFS_CLIENT_IP)
EOF

##################################################################
# Initialize NFS server
##################################################################
testbus_test_begin server-init

testbus_trace "server: setting up NFS server"

# I would have loved to use yast2 for this, but right now it always
# wants _at least_ a pipe on stdout, preferably a tty. If you make it
# write to anything else, it'll just die quietly.
if $USE_YAST; then
	testbus_exit_failure "not implemented"
else
	# This is icky:
	__run_server /sbin/rpcbind || true

	run_server /bin/mkdir -p /srv/nfs/dir{1,2,3,4}
	testbus_trace "server: starting nfs-server"
	run_server /etc/init.d/nfsserver start
	run_server /sbin/chkconfig nfsserver on
fi

server_write_exports - <<EOF
/srv/nfs/dir1	*(ro)
/srv/nfs/dir2	*(rw,no_root_squash)
/srv/nfs/dir3	*(rw)
EOF

server_update_hosts "$NFS_CLIENT_IP	$NFS_CLIENT_NAME nfs-client.testbus.opensuse.org"

##################################################################
# Initialize NFS server
##################################################################
testbus_test_begin client-init

client_update_hosts "$NFS_SERVER_IP	$NFS_SERVER_NAME nfs-server.testbus.opensuse.org"
run_client /usr/sbin/showmount -e nfs-server.testbus.opensuse.org

run_client /bin/mkdir -p /mnt/nfs{1,2,3,4}

testbus_test_success

##################################################################
# Basic testing of NFS mounts
##################################################################
testbus_group_begin mount-tests

testbus_test_begin byname
run_client /bin/mount $NFS_SERVER_NAME:/srv/nfs/dir1 /mnt/nfs1
run_client /bin/umount /mnt/nfs1

testbus_test_begin byaddr
run_client /bin/mount $NFS_SERVER_IP:/srv/nfs/dir1 /mnt/nfs1
run_client /bin/umount /mnt/nfs1

function mount_should_fail {

	testname=$1
	server_dir=$2
	client_dir=$3

	testbus_test_begin $testname
	if __run_client /bin/mount $NFS_SERVER_IP:$server_dir $client_dir; then
		testbus_test_failure "This mount attempt should have failed"
		umount $client_dir
	else
		testbus_test_success
	fi
}

mount_should_fail non-exported /srv/nfs/dir4 /mnt/nfs4

# These are "exported" for the NFSv4 virtual file handle space,
# but should these really be available to NFSv2/v3 clients as well?
mount_should_fail non-exported /srv/nfs /mnt/nfs4
mount_should_fail non-exported /srv /mnt/nfs4

testbus_group_finish SUCCESS


##################################################################
# Functions that help repeated testing with different options
##################################################################
function nfs_test_readonly {

	server_dir=$1
	client_dir=$2

	testbus_test_begin readonly
	run_server /bin/rm -f $server_dir/readonly-test
	run_client /bin/mount $NFS_SERVER_NAME:$server_dir $client_dir
	__run_client /bin/touch $client_dir/readonly-test &&
		testbus_test_failure "file system should be read-only, but succeeded in creating file"
	run_client /bin/umount $client_dir

	testbus_test_success
}

function nfs_test_readwrite {

	server_dir=$1
	client_dir=$2

	testbus_test_begin readwrite
	run_server /bin/rm -f $server_dir/readwrite-test
	run_client /bin/mount $NFS_SERVER_NAME:$server_dir $client_dir
	__run_client /bin/touch $client_dir/readwrite-test ||
		testbus_test_failure "file system should be read-write, but was unable to create the file"
	run_client /bin/umount $client_dir

	testbus_test_success
}

function nfs_test_rootsquash {

	server_dir=$1
	client_dir=$2
	squash_id=${3:-65534}

	file=any/rootsquash-test

	testbus_test_begin rootsquash
	run_server /bin/mkdir -m 01777 -p $server_dir/any
	run_server /bin/rm -f $server_dir/$file
	run_client /bin/mount $NFS_SERVER_NAME:$server_dir $client_dir
	if run_client /bin/touch $client_dir/$file; then
		owner=`__run_client /bin/stat -c %%u $client_dir/$file`
		if [ $? -ne 0 ]; then
			testbus_test_failure "failed to run stat command on client"
		elif [ "$owner" -ne $squash_id ]; then
			testbus_test_failure "file system should have root-squashing enabled. new file has owner uid=\"$owner\" (expected $squash_id)"
		fi
	fi
	run_client /bin/umount $client_dir

	testbus_test_success
}

function nfs_test_norootsquash {

	server_dir=$1
	client_dir=$2

	testbus_test_begin norootsquash
	run_server /bin/rm -f $server_dir/rootsquash-test
	run_client /bin/mount $NFS_SERVER_NAME:$server_dir $client_dir
	if run_client /bin/touch $client_dir/rootsquash-test; then
		owner=`__run_client /bin/stat -c %%u $client_dir/rootsquash-test`
		if [ $? -ne 0 ]; then
			testbus_test_failure "failed to run stat command on client"
		elif [ "$owner" -ne 0 ]; then
			testbus_test_failure "file system should have no root-squashing enabled. new file has owner uid=\"$owner\""
		fi
	fi
	run_client /bin/umount $client_dir

	testbus_test_success
}

testbus_group_begin export-flags

nfs_test_readonly /srv/nfs/dir1 /mnt/nfs1
nfs_test_readwrite /srv/nfs/dir2 /mnt/nfs2
nfs_test_norootsquash /srv/nfs/dir2 /mnt/nfs2
nfs_test_rootsquash /srv/nfs/dir3 /mnt/nfs3

testbus_group_finish SUCCESS


##################################################################
# Test ip net/mask matching in exports
##################################################################
testbus_group_begin netmask-exports

server_write_exports - <<EOF
/srv/nfs/dir1	*(ro)
/srv/nfs/dir1	10.0.0.0/8(rw,no_root_squash)
EOF

nfs_test_norootsquash /srv/nfs/dir1 /mnt/nfs1

# And now the other way around
server_write_exports - <<EOF
/srv/nfs/dir1	10.0.0.0/8(ro) *(rw,no_root_squash)
EOF

nfs_test_readonly /srv/nfs/dir1 /mnt/nfs1

testbus_group_finish SUCCESS

##################################################################
# Test domain matching
##################################################################
testbus_group_begin domain-wildcard

server_write_exports - <<EOF
/srv/nfs/dir1	*(ro)
/srv/nfs/dir1	*.testbus.opensuse.org(rw,no_root_squash)
EOF

nfs_test_norootsquash /srv/nfs/dir1 /mnt/nfs1

testbus_group_finish SUCCESS

##################################################################
# Test squashid
##################################################################
testbus_group_begin squashid

server_write_exports - <<EOF
/srv/nfs/dir1	*(rw,root_squash,anonuid=60000)
EOF

nfs_test_rootsquash /srv/nfs/dir1 /mnt/nfs1 60000

testbus_group_finish SUCCESS

testbus_exit
